version: '3'

services:
  bm:
    build:
      dockerfile: deployment/server/Dockerfile
      context: ../../
    environment:
      - BM_ROOT_DIR=/app
      - BM_SERVER_CONFIG=/configs/server_config.json
      - BM_MIGRATIONS_PATH=/migrations/
      - BM_CLI_CLIENT_CONFIG=configs/cli_client_config.json
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ../../socket/:/socket/:rw

  db:
    image: postgres:14-alpine
    container_name: bm_postgres_1
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: bm
      POSTGRES_USER: bm
      POSTGRES_PASSWORD: bm_password
      PGDATA: /data
    networks:
      - backend
    volumes:
      - postgres_data:/data

networks:
  backend:

volumes:
  postgres_data: